"""Serve the AsyncAPI document over HTTP — the egress twin of ``/openapi.json``.

The document itself is generated by ``asyncapi_document(catalog, router)`` in
``forze_socketio`` (integration packages cannot import each other, so the app —
which imports both — composes them):

    from forze_socketio import asyncapi_document

    attach_asyncapi_route(router, document=asyncapi_document(catalog, sio_router))

Client types then come from standard AsyncAPI tooling pointed at the endpoint,
exactly like OpenAPI codegen — e.g.
``npx @asyncapi/cli generate models typescript http://localhost:8000/asyncapi.json``
— which is why no maintained client SDK ships: the served contract is the product.
"""

from forze_fastapi._compat import require_fastapi

require_fastapi()

# ....................... #

from collections.abc import Mapping
from copy import deepcopy
from typing import Any

from fastapi import APIRouter
from fastapi.responses import JSONResponse

from forze.base.exceptions import exc

# ----------------------- #

__all__ = [
    "attach_asyncapi_route",
]


def attach_asyncapi_route(
    router: APIRouter,
    *,
    document: Mapping[str, Any],
    path: str = "/asyncapi.json",
) -> APIRouter:
    """Attach a GET endpoint serving *document* as the app's AsyncAPI contract.

    The document is static for the process lifetime (the catalog and command
    router it is generated from are frozen), so it is validated and captured once
    at attach time. Excluded from the OpenAPI schema, mirroring ``/openapi.json``.
    """

    if "asyncapi" not in document:
        # the one-key sanity check: catching a swapped/misbuilt dict at wiring time
        # beats serving a non-contract to a code generator
        raise exc.configuration(
            "attach_asyncapi_route expects an AsyncAPI document (missing 'asyncapi' key) — "
            "build it with asyncapi_document(catalog, router) from forze_socketio"
        )

    captured = deepcopy(dict(document))  # a snapshot — later caller-side mutation must not leak

    async def asyncapi_endpoint() -> JSONResponse:
        return JSONResponse(captured)

    router.get(
        path,
        name="asyncapi_document",
        include_in_schema=False,
    )(asyncapi_endpoint)

    return router
