---
exclude_paths:
  - "tests/**"
  - ".agents/**"
  - ".cursor/**"
  - ".vscode/**"
  - ".github/**"
  - ".pre-commit/**"
  - ".pre-commit-config.yaml"
  - "pages/**"
  - ".greptile/**"
  - ".sourcery.yaml"
  - "justfile"
  - "skills/**"
