"""In-memory mock integration for Forze contracts.

`forze_mock` provides dependency wiring and adapters for running Forze without
external infrastructure. It is intended for development and tests.
"""

from .adapters import (
    MockAnalyticsAdapter,
    MockCacheAdapter,
    MockCounterAdapter,
    MockDistributedLockAdapter,
    MockDocumentAdapter,
    MockDurableFunctionEventAdapter,
    MockDurableFunctionStepAdapter,
    MockDurableWorkflowCommandAdapter,
    MockDurableWorkflowQueryAdapter,
    MockDurableWorkflowScheduleCommandAdapter,
    MockDurableWorkflowScheduleQueryAdapter,
    MockFederatedSearchAdapter,
    MockHttpRegistry,
    MockHttpServiceAdapter,
    MockHubSearchAdapter,
    MockIdempotencyAdapter,
    MockKeyManagement,
    MockPubSubAdapter,
    MockQueueAdapter,
    MockSearchAdapter,
    MockSearchCommandAdapter,
    MockSearchResultSnapshotAdapter,
    MockState,
    MockStorageAdapter,
    MockStreamAdapter,
    MockStreamGroupAdapter,
    MockStrictTxManagerAdapter,
    MockTxManagerAdapter,
    RecordingAuthnEventSink,
)
from .adapters.identity import (
    MockSecretsPort,
    MockTenantManagementPort,
    MockTenantResolverPort,
)
from .adapters.embeddings import MockHashEmbeddingsProvider
from .execution import (
    MockDepsModule,
    MockRouteConfig,
    MockRoutedStateDepKey,
    MockStateDepKey,
)
from .simulation import (
    OpSpec,
    RealIOForbidden,
    SimulationDeadlock,
    SimulationEventLoop,
    SimulationTimeSource,
    generate_workload,
    run_simulation,
    run_workload,
    simulate_workload,
)
from .tenancy import (
    MockRoutedStateRegistry,
    MockTenancyMixin,
    mock_routed_state_lifecycle_step,
    partition_namespace,
    resolve_mock_namespace,
)

# ----------------------- #

__all__ = [
    "MockState",
    "MockStateDepKey",
    "MockRoutedStateDepKey",
    "MockRouteConfig",
    "MockDepsModule",
    "MockRoutedStateRegistry",
    "mock_routed_state_lifecycle_step",
    "MockTenancyMixin",
    "partition_namespace",
    "resolve_mock_namespace",
    "MockDocumentAdapter",
    "MockAnalyticsAdapter",
    "MockSearchAdapter",
    "MockSearchCommandAdapter",
    "MockSearchResultSnapshotAdapter",
    "MockHubSearchAdapter",
    "MockFederatedSearchAdapter",
    "MockCounterAdapter",
    "MockCacheAdapter",
    "MockIdempotencyAdapter",
    "MockStorageAdapter",
    "MockTxManagerAdapter",
    "MockStrictTxManagerAdapter",
    "MockQueueAdapter",
    "MockPubSubAdapter",
    "MockStreamAdapter",
    "MockStreamGroupAdapter",
    "MockDistributedLockAdapter",
    "MockHttpServiceAdapter",
    "MockHttpRegistry",
    "MockDurableWorkflowCommandAdapter",
    "MockDurableWorkflowQueryAdapter",
    "MockDurableWorkflowScheduleCommandAdapter",
    "MockDurableWorkflowScheduleQueryAdapter",
    "MockDurableFunctionEventAdapter",
    "MockDurableFunctionStepAdapter",
    "MockSecretsPort",
    "MockKeyManagement",
    "MockTenantResolverPort",
    "MockTenantManagementPort",
    "MockHashEmbeddingsProvider",
    "RecordingAuthnEventSink",
    "run_simulation",
    "SimulationEventLoop",
    "SimulationTimeSource",
    "SimulationDeadlock",
    "RealIOForbidden",
    "OpSpec",
    "generate_workload",
    "run_workload",
    "simulate_workload",
]
