"""In-memory mock integration for Forze contracts.

`forze_mock` provides dependency wiring and adapters for running Forze without
external infrastructure. It is intended for development and tests.
"""

from .adapters import (
    MockAckStreamGroupAdapter,
    MockAckStreamGroupAdminAdapter,
    MockAnalyticsAdapter,
    MockCacheAdapter,
    MockCommitStreamGroupAdapter,
    MockCommitStreamGroupAdminAdapter,
    MockCounterAdapter,
    MockDistributedLockAdapter,
    MockDocumentAdapter,
    MockDurableFunctionEventAdapter,
    MockDurableFunctionStepAdapter,
    MockDurableRunStore,
    MockDurableScheduleStore,
    MockDurableWorkflowCommandAdapter,
    MockDurableWorkflowQueryAdapter,
    MockDurableWorkflowScheduleCommandAdapter,
    MockDurableWorkflowScheduleQueryAdapter,
    MockFederatedSearchAdapter,
    MockHttpRegistry,
    MockHttpServiceAdapter,
    MockHubSearchAdapter,
    MockIdempotencyAdapter,
    MockKeyManagement,
    MockProcedureAdapter,
    MockProcedureHandler,
    MockProcedureRegistry,
    MockPubSubAdapter,
    MockQueryParamsRegistry,
    MockQueryParamsSource,
    MockQueueAdapter,
    MockSearchAdapter,
    MockSearchCommandAdapter,
    MockSearchResultSnapshotAdapter,
    MockState,
    MockStorageAdapter,
    MockStreamAdapter,
    MockStrictTxManagerAdapter,
    MockTxManagerAdapter,
    RecordingAuthnEventSink,
)
from .adapters.embeddings import MockHashEmbeddingsProvider
from .adapters.identity import (
    MockSecretsPort,
    MockTenantManagementPort,
    MockTenantResolverPort,
)
from .execution import (
    MockDepsModule,
    MockRouteConfig,
    MockRoutedStateDepKey,
    MockStateDepKey,
)
from .tenancy import (
    MockRoutedStateRegistry,
    MockTenancyMixin,
    mock_routed_state_lifecycle_step,
    partition_namespace,
    resolve_mock_namespace,
)

# ----------------------- #

__all__ = [
    "MockState",
    "MockStateDepKey",
    "MockRoutedStateDepKey",
    "MockRouteConfig",
    "MockDepsModule",
    "MockRoutedStateRegistry",
    "mock_routed_state_lifecycle_step",
    "MockTenancyMixin",
    "partition_namespace",
    "resolve_mock_namespace",
    "MockDocumentAdapter",
    "MockAnalyticsAdapter",
    "MockProcedureAdapter",
    "MockProcedureRegistry",
    "MockProcedureHandler",
    "MockQueryParamsRegistry",
    "MockQueryParamsSource",
    "MockSearchAdapter",
    "MockSearchCommandAdapter",
    "MockSearchResultSnapshotAdapter",
    "MockHubSearchAdapter",
    "MockFederatedSearchAdapter",
    "MockCounterAdapter",
    "MockCacheAdapter",
    "MockIdempotencyAdapter",
    "MockStorageAdapter",
    "MockTxManagerAdapter",
    "MockStrictTxManagerAdapter",
    "MockQueueAdapter",
    "MockPubSubAdapter",
    "MockStreamAdapter",
    "MockAckStreamGroupAdapter",
    "MockAckStreamGroupAdminAdapter",
    "MockCommitStreamGroupAdapter",
    "MockCommitStreamGroupAdminAdapter",
    "MockDistributedLockAdapter",
    "MockHttpServiceAdapter",
    "MockHttpRegistry",
    "MockDurableWorkflowCommandAdapter",
    "MockDurableWorkflowQueryAdapter",
    "MockDurableWorkflowScheduleCommandAdapter",
    "MockDurableWorkflowScheduleQueryAdapter",
    "MockDurableFunctionEventAdapter",
    "MockDurableFunctionStepAdapter",
    "MockDurableRunStore",
    "MockDurableScheduleStore",
    "MockSecretsPort",
    "MockKeyManagement",
    "MockTenantResolverPort",
    "MockTenantManagementPort",
    "MockHashEmbeddingsProvider",
    "RecordingAuthnEventSink",
]
