"""Execution kernel, dependency injection, and lifecycle."""

from .context import (
    ExecutionContext,
    InvocationMetadata,
    bind_deadline,
    current_deadline,
    remaining_time,
)
from .domain import (
    DomainEventHandler,
    DomainEventHandlerFactory,
    DomainEventRegistry,
    DomainEventsDepsModule,
    InProcessDomainEventDispatcher,
    outbox_event_handler,
)
from forze.application.contracts.deps import Deps, DepsModule

from .deps import (
    DepsRegistry,
    FrozenDeps,
    FrozenDepsRegistry,
    ResolutionContext,
    ResolutionTracer,
    resolution_tracer_from_flag,
)
from .lifecycle import LifecyclePlan
from .operations import (
    OperationCatalogEntry,
    OperationDescriptor,
    OperationKind,
    OperationPlan,
    WiringFailure,
    WiringReport,
    check_facade_factory_wiring,
    check_wiring,
)
from .operations.registry import FrozenOperationRegistry, OperationRegistry
from .resilience import (
    InMemoryCircuitBreakerStore,
    InProcessResilienceExecutor,
    ResilienceDepsModule,
    builtin_default_policies,
    default_resilience_executor,
    occ_retry,
    resolve_resilience_executor,
)
from .observability import (
    BREAKER_STATE_GAUGE,
    BULKHEAD_LIMIT_GAUGE,
    BULKHEAD_QUEUE_GAUGE,
    CRYPTO_CACHE_HITS_COUNTER,
    CRYPTO_COLD_MISS_COUNTER,
    CRYPTO_DATA_KEYS_GENERATED_COUNTER,
    CRYPTO_DATA_KEYS_UNWRAPPED_COUNTER,
    DURATION_HISTOGRAM,
    OPERATIONS_COUNTER,
    RESILIENCE_EVENTS_COUNTER,
    instrument_crypto,
    instrument_operations,
    instrument_resilience,
    instrument_tenant_pools,
)
from .runtime import DeploymentProfile, ExecutionRuntime
from .assemble import build_runtime
from .crypto import CryptoDepsModule
from .saga import (
    InProcessSagaExecutor,
    SagaDepsModule,
    default_saga_executor,
    resolve_saga_executor,
    run_saga,
)
from .tracing import (
    RuntimeTrace,
    RuntimeTraceValidationError,
    RuntimeTraceValidator,
    RuntimeTracer,
    TracedOperationResult,
    TraceExpectation,
    TracingEvent,
    TracingViolation,
    active_deps,
    assert_runtime_trace_valid,
    assert_trace_contains,
    assert_trace_equals,
    run_traced_operation,
    runtime_tracer_from_flag,
    validate_runtime_trace,
)

# ----------------------- #

__all__ = [
    "build_runtime",
    "InvocationMetadata",
    "bind_deadline",
    "current_deadline",
    "remaining_time",
    "Deps",
    "DepsModule",
    "DepsRegistry",
    "FrozenDeps",
    "FrozenDepsRegistry",
    "ResolutionContext",
    "ResolutionTracer",
    "RuntimeTracer",
    "resolution_tracer_from_flag",
    "runtime_tracer_from_flag",
    "DomainEventHandler",
    "DomainEventHandlerFactory",
    "DomainEventRegistry",
    "DomainEventsDepsModule",
    "CryptoDepsModule",
    "ExecutionContext",
    "ExecutionRuntime",
    "DeploymentProfile",
    "FrozenOperationRegistry",
    "InMemoryCircuitBreakerStore",
    "InProcessDomainEventDispatcher",
    "InProcessResilienceExecutor",
    "outbox_event_handler",
    "LifecyclePlan",
    "OperationCatalogEntry",
    "OperationDescriptor",
    "OperationKind",
    "OperationPlan",
    "OperationRegistry",
    "WiringFailure",
    "WiringReport",
    "check_facade_factory_wiring",
    "check_wiring",
    "instrument_operations",
    "instrument_resilience",
    "instrument_tenant_pools",
    "instrument_crypto",
    "OPERATIONS_COUNTER",
    "DURATION_HISTOGRAM",
    "RESILIENCE_EVENTS_COUNTER",
    "BREAKER_STATE_GAUGE",
    "BULKHEAD_QUEUE_GAUGE",
    "BULKHEAD_LIMIT_GAUGE",
    "CRYPTO_DATA_KEYS_GENERATED_COUNTER",
    "CRYPTO_DATA_KEYS_UNWRAPPED_COUNTER",
    "CRYPTO_CACHE_HITS_COUNTER",
    "CRYPTO_COLD_MISS_COUNTER",
    "ResilienceDepsModule",
    "builtin_default_policies",
    "default_resilience_executor",
    "occ_retry",
    "resolve_resilience_executor",
    "InProcessSagaExecutor",
    "SagaDepsModule",
    "default_saga_executor",
    "resolve_saga_executor",
    "run_saga",
    "RuntimeTrace",
    "RuntimeTraceValidationError",
    "RuntimeTraceValidator",
    "TraceExpectation",
    "TracedOperationResult",
    "TracingEvent",
    "TracingViolation",
    "active_deps",
    "assert_runtime_trace_valid",
    "assert_trace_contains",
    "assert_trace_equals",
    "run_traced_operation",
    "validate_runtime_trace",
]
