"""Authentication contracts: orchestration port, verifier ports, principal resolver, and value objects.

Lifecycle and provisioning ports live in sibling contract groups
(:mod:`forze.application.contracts.authn_lifecycle`,
:mod:`forze.application.contracts.authn_provisioning`) so external IdP integrations can
implement only what they care about.
"""

from .deps import (
    ApiKeyLifecycleDepKey,
    ApiKeyLifecycleDepPort,
    ApiKeyVerifierDepKey,
    ApiKeyVerifierDepPort,
    AuthnDepKey,
    AuthnDepPort,
    AuthnDeps,
    PasswordAccountProvisioningDepKey,
    PasswordAccountProvisioningDepPort,
    PasswordLifecycleDepKey,
    PasswordLifecycleDepPort,
    PasswordVerifierDepKey,
    PasswordVerifierDepPort,
    PrincipalDeactivationDepKey,
    PrincipalDeactivationDepPort,
    PrincipalEligibilityDepKey,
    PrincipalEligibilityDepPort,
    PrincipalResolverDepKey,
    PrincipalResolverDepPort,
    TokenLifecycleDepKey,
    TokenLifecycleDepPort,
    TokenVerifierDepKey,
    TokenVerifierDepPort,
)
from .ports import (
    ApiKeyLifecyclePort,
    ApiKeyVerifierPort,
    AuthnPort,
    PasswordAccountProvisioningPort,
    PasswordLifecyclePort,
    PasswordVerifierPort,
    PrincipalDeactivationPort,
    PrincipalEligibilityPort,
    PrincipalResolverPort,
    TokenLifecyclePort,
    TokenVerifierPort,
)
from .specs import AuthnMethod, AuthnSpec
from .value_objects import (
    AccessTokenCredentials,
    ApiKeyCredentials,
    AuthnIdentity,
    AuthnResult,
    CredentialLifetime,
    IssuedAccessToken,
    IssuedApiKey,
    IssuedRefreshToken,
    IssuedTokens,
    PasswordCredentials,
    RefreshTokenCredentials,
    VerifiedAssertion,
)

# ----------------------- #

__all__ = [
    "AccessTokenCredentials",
    "ApiKeyCredentials",
    "ApiKeyLifecycleDepKey",
    "ApiKeyLifecycleDepPort",
    "ApiKeyLifecyclePort",
    "ApiKeyVerifierDepKey",
    "ApiKeyVerifierDepPort",
    "ApiKeyVerifierPort",
    "AuthnDepKey",
    "AuthnDepPort",
    "AuthnDeps",
    "AuthnIdentity",
    "AuthnResult",
    "AuthnMethod",
    "AuthnPort",
    "AuthnSpec",
    "CredentialLifetime",
    "IssuedAccessToken",
    "IssuedApiKey",
    "IssuedRefreshToken",
    "IssuedTokens",
    "PasswordAccountProvisioningDepKey",
    "PasswordAccountProvisioningDepPort",
    "PasswordAccountProvisioningPort",
    "PasswordCredentials",
    "PasswordLifecycleDepKey",
    "PasswordLifecycleDepPort",
    "PasswordLifecyclePort",
    "PasswordVerifierDepKey",
    "PasswordVerifierDepPort",
    "PasswordVerifierPort",
    "PrincipalDeactivationDepKey",
    "PrincipalDeactivationDepPort",
    "PrincipalDeactivationPort",
    "PrincipalEligibilityDepKey",
    "PrincipalEligibilityDepPort",
    "PrincipalEligibilityPort",
    "PrincipalResolverDepKey",
    "PrincipalResolverDepPort",
    "PrincipalResolverPort",
    "RefreshTokenCredentials",
    "TokenLifecycleDepKey",
    "TokenLifecycleDepPort",
    "TokenLifecyclePort",
    "TokenVerifierDepKey",
    "TokenVerifierDepPort",
    "TokenVerifierPort",
    "VerifiedAssertion",
]
