"""Authentication contracts: orchestration port, verifier ports, principal resolver, and value objects.

Lifecycle and provisioning ports live in sibling contract groups
(:mod:`forze.application.contracts.authn_lifecycle`,
:mod:`forze.application.contracts.authn_provisioning`) so external IdP integrations can
implement only what they care about.
"""

from .deps import (
    ApiKeyLifecycleDepKey,
    ApiKeyLifecycleDepPort,
    ApiKeyVerifierDepKey,
    ApiKeyVerifierDepPort,
    AuthnDepKey,
    AuthnDepPort,
    AuthnDeps,
    AuthnEventSinkDepKey,
    AuthnEventSinkDepPort,
    PasswordAccountProvisioningDepKey,
    PasswordAccountProvisioningDepPort,
    PasswordLifecycleDepKey,
    PasswordLifecycleDepPort,
    PasswordResetDepKey,
    PasswordResetDepPort,
    PasswordVerifierDepKey,
    PasswordVerifierDepPort,
    PrincipalDeactivationDepKey,
    PrincipalDeactivationDepPort,
    PrincipalEligibilityDepKey,
    PrincipalEligibilityDepPort,
    PrincipalResolverDepKey,
    PrincipalResolverDepPort,
    TokenLifecycleDepKey,
    TokenLifecycleDepPort,
    TokenVerifierDepKey,
    TokenVerifierDepPort,
    resolve_authn_event_emitter,
)
from .events import (
    AuthnEvent,
    AuthnEventEmitter,
    AuthnEventKind,
    AuthnEventSink,
    emit_safe,
    login_digest,
)
from .ports import (
    ApiKeyLifecyclePort,
    ApiKeyVerifierPort,
    AuthnPort,
    PasswordAccountProvisioningPort,
    PasswordLifecyclePort,
    PasswordResetPort,
    PasswordVerifierPort,
    PrincipalDeactivationPort,
    PrincipalEligibilityPort,
    PrincipalResolverPort,
    TokenLifecyclePort,
    TokenVerifierPort,
)
from .specs import AuthnMethod, AuthnSpec
from .value_objects import (
    ACT_CLAIM,
    AccessTokenCredentials,
    ApiKeyCredentials,
    ApiKeyInfo,
    AuthnIdentity,
    AuthnResult,
    ClientIdentity,
    CredentialLifetime,
    IssuedAccessToken,
    IssuedApiKey,
    IssuedInvite,
    IssuedPasswordReset,
    IssuedRefreshToken,
    IssuedTokens,
    PasswordCredentials,
    RefreshTokenCredentials,
    VerifiedAssertion,
)

# ----------------------- #

__all__ = [
    "AccessTokenCredentials",
    "ApiKeyCredentials",
    "ApiKeyLifecycleDepKey",
    "ApiKeyLifecycleDepPort",
    "ApiKeyLifecyclePort",
    "ApiKeyVerifierDepKey",
    "ApiKeyVerifierDepPort",
    "ApiKeyVerifierPort",
    "AuthnDepKey",
    "AuthnDepPort",
    "AuthnDeps",
    "AuthnEvent",
    "AuthnEventEmitter",
    "AuthnEventKind",
    "AuthnEventSink",
    "AuthnEventSinkDepKey",
    "AuthnEventSinkDepPort",
    "AuthnIdentity",
    "AuthnResult",
    "ClientIdentity",
    "AuthnMethod",
    "AuthnPort",
    "AuthnSpec",
    "CredentialLifetime",
    "emit_safe",
    "login_digest",
    "resolve_authn_event_emitter",
    "IssuedAccessToken",
    "ApiKeyInfo",
    "IssuedApiKey",
    "IssuedInvite",
    "IssuedPasswordReset",
    "IssuedRefreshToken",
    "IssuedTokens",
    "PasswordAccountProvisioningDepKey",
    "PasswordAccountProvisioningDepPort",
    "PasswordAccountProvisioningPort",
    "PasswordCredentials",
    "PasswordLifecycleDepKey",
    "PasswordLifecycleDepPort",
    "PasswordLifecyclePort",
    "PasswordResetDepKey",
    "PasswordResetDepPort",
    "PasswordResetPort",
    "PasswordVerifierDepKey",
    "PasswordVerifierDepPort",
    "PasswordVerifierPort",
    "PrincipalDeactivationDepKey",
    "PrincipalDeactivationDepPort",
    "PrincipalDeactivationPort",
    "PrincipalEligibilityDepKey",
    "PrincipalEligibilityDepPort",
    "PrincipalEligibilityPort",
    "PrincipalResolverDepKey",
    "PrincipalResolverDepPort",
    "PrincipalResolverPort",
    "RefreshTokenCredentials",
    "TokenLifecycleDepKey",
    "TokenLifecycleDepPort",
    "TokenLifecyclePort",
    "TokenVerifierDepKey",
    "TokenVerifierDepPort",
    "TokenVerifierPort",
    "ACT_CLAIM",
    "VerifiedAssertion",
]
