style: {
    fill: transparent
}

vars: {
    d2-config: {
        pad: 24
    }
}

direction: down

Interface: {
    shape: rectangle
    label: Interface

    routers: HTTP routers
    ws: WebSocket handlers
}

Infrastructure: {
    shape: rectangle
    label: Infrastructure

    adapters: Adapters
    clients: External clients
}

Application: {
    shape: rectangle
    label: Application

    handlers: Handlers & facades
    contracts: Contracts
    context: Execution context
}

Domain: {
    shape: rectangle
    label: Domain

    models: Domain / value models
    validation: Validators & invariants
}

Interface.routers -> Application.handlers: invoke
Interface.ws -> Application.handlers: invoke
Infrastructure.adapters -> Application.contracts: implement
Application.handlers -> Domain.models: use
Application.context -> Application.contracts
Application.handlers -> Application.context: resolve dependencies
Infrastructure.adapters -> Infrastructure.clients: use
Domain.models -> Domain.validation: check
