style: {
    fill: transparent
}

vars: {
    d2-config: {
        pad: 50
    }
}

direction: right

Guards: {
    shape: rectangle
    label: Guard chain
}

Middlewares: {
    shape: rectangle
    label: Middleware chain
}

Usecase: {
    shape: circle
    label: Core usecase
}

Effects: {
    shape: rectangle
    label: Effect chain
}

AfterCommit: {
    shape: rectangle
    label: Side effects after commit
}

Guards -> Middlewares -> Usecase -> Effects
Usecase -> AfterCommit: transactional flow