# Operation composition: guards, middlewares, core, effects

style: {
    fill: transparent
}

vars: {
    d2-config: {
        pad: 50
    }
}

direction: right

Usecase.shape: circle

Guards -> Middlewares -> Usecase -> Effects