set quiet
set shell := ["bash", "-cu"]

# ----------------------- #
# Paths / constants

_pwd := justfile_directory()
_cwd := join(_pwd, "pages")

_d2_dir := join(_cwd, "diagrams")
_d2_light_build_dir := join(_cwd, "docs", "assets", "diagrams", "light")
_d2_dark_build_dir := join(_cwd, "docs", "assets", "diagrams", "dark")
_d2_light_flags := "--center"
_d2_dark_flags := "--theme 200 --center"

# ----------------------- #

# Serve the documentation with live reload
serve:
    uv run mkdocs serve --livereload

# Build the documentation
build path="site": diagrams
    uv run mkdocs build -d {{ _pwd }}/{{ path }}

diagrams:
    mkdir -p {{ _d2_light_build_dir }}
    mkdir -p {{ _d2_dark_build_dir }}

    for f in {{ _d2_dir }}/*.d2; do \
        d2 "$f" "{{ _d2_light_build_dir }}/$(basename "${f%.d2}.svg")" {{ _d2_light_flags }}; \
        d2 "$f" "{{ _d2_dark_build_dir }}/$(basename "${f%.d2}.svg")" {{ _d2_dark_flags }}; \
    done