site_name: Forze
site_url: https://morzecrew.github.io/forze
repo_url: https://github.com/morzecrew/forze

theme:
  name: shadcn
  icon: null
  show_stargazers: false
  topbar_sections: false
  show_title: true
  pygments_style:
    light: shadcn-light
    dark: github-dark
  show_datetime: true

extra_css:
  - css/extra.css

plugins:
  - d2
  - search
  - mkdocstrings
  - pygments

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.blocks.caption

nav:
  - Home: index.md
  - Installation: installation.md
  - Core Concepts: core-concepts.md
  - Integrations:
    - FastAPI: integrations/fastapi.md
    - PostgreSQL: integrations/postgres.md
    - Redis: integrations/redis.md
    - S3: integrations/s3.md