name: Publish documentation to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency: pages

jobs:
  build:
    name: Build the documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: |
            uv.lock
            pyproject.toml
      
      - name: Install just
        uses: extractions/setup-just@v3
      
      - name: Install dependencies
        run: uv sync --group docs

      - name: Restore site cache
        uses: actions/cache/restore@v4
        with:
          path: .cache
          key: mkdocs-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('pages/**') }}
          restore-keys: |
            mkdocs-${{ runner.os }}-${{ github.ref_name }}-
            mkdocs-${{ runner.os }}-

      - name: Build site
        run: just pages build site

      - name: Save site cache
        if: success()
        uses: actions/cache/save@v4
        with:
          path: .cache
          key: mkdocs-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('pages/**') }}

      - name: Upload pages artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site
  
  deploy:
    name: Deploy site to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      